version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Building website..."
      - npm install || echo "No dependencies"
artifacts:
  files:
    - '**/*'

post_build:
  commands:
    - echo "Invalidating CloudFront cache..."
    - aws cloudfront create-invalidation \
        --distribution-id E6RKLL5U2JUMK \
        --paths "/*"
