version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Building website..."
      - npm install || echo "No dependencies"
artifacts:
  files:
    - '**/*'
